### PR TITLE
Update installation instructions

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-2346

### CODE REVIEW

**Comment by acoburn** [comment]
@dannylamb @bseeger let me know if you think these changes to the installation instructions are suitably clear.

**Comment by dannylamb** [comment]
Defnitely not a blocker here, but maybe you want the badges to be at the very top of the README?  https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/pull/122/files#diff-04c6e90faac2675aa89e2176d2eec7d8R7

**Comment by acoburn** [comment]
@dannylamb w/r/t the badges, do you mean put the badges above the title "Fedora Messaging Application Toolbox"? at present, they're just under brief description, which seems like a pretty good place for them.

**Comment by dannylamb** [comment]
If you like where they are, then that's where they should be.  Just making sure they're not there by accident.

**Comment by bseeger** [comment]
These changes look good to me.  I've no opinion on the badge location other then to say I never really paid attention to them before and didn't know what you were referring to when you referenced the Maven Central badge (not that it was hard to figure out).  Either I'm now in the loop that everyone else is in, or others might be confused as well. Not sure which is true for most folks.

**Comment by dannylamb** [comment]
@acoburn @bseeger It feels silly to wait for Travis on a README pull, but I'll merge once Travis turns green.  :+1:

**Comment by acoburn** [comment]
I'd say that a significant number of people who may want to use this code won't know what "Maven Central" is, and yet if we refer to the releases page on github, there's nothing to download (other than source code that would need to be compiled -- which is certainly no better). I think the balance I was trying to strike was this -- if you are familiar with the typical Java build/dependency infrastructure, you'll know what's being described, and if you're not, you can just look at the specific commands. In my mind, it's kind of like making reference to OSGi -- that really isn't going to mean anything to most people, and that's probably a good thing :-) But if you do know what OSGi is all about, you would probably want to know. I also see the README as a constant work in progress, and we should keep working at making it clearer (without being too verbose).

**Comment by dannylamb** [comment]
@acoburn It's tricky when you're building on top of technologies that go deep like OSGi and Karaf.  You can't be on the hook for a full tutorial on them, but you at least need to give them a nod.

**Pull request merged**
