### PR TITLE
Added PAX Exam to testing framework

### PR DESCRIPTION
**Pull request by acoburn**
See: https://jira.duraspace.org/browse/FCREPO-1897

  * Moved features.xml provisioning into its own module
  * Added PAX-Exam to testing framework
  * Updated documentation

### CODE REVIEW

**Comment by awoods** [comment]
Does this PR render the existing https://github.com/fcrepo4-labs/fcrepo-karaf project obsolete?

**Comment by acoburn** [comment]
Not at all. fcrepo-karaf is for provisioning the Fedora artifacts, which are independent of the camel toolbox

**Comment by awoods** [comment]
The naming conflict introduces confusion. How do you feel about renaming this current module?

**Comment by acoburn** [comment]
I am not convinced that there will be confusion, as these use different `groupId`s, but I have renamed the `fcrepo-karaf` module to `toolbox-features`, following another convention for feature repositories that I'm familiar with.

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/commit/8523ac995c6e0ab9e7ba40582b11b397b1ef2b0e

**Pull request closed without merging**
