### PR TITLE
Changes to work with Fedora-Camel 5.0.0

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: https://jira.duraspace.org/browse/FCREPO-2787

Related PR: https://github.com/fcrepo4-exts/fcrepo-camel/pull/150

# What does this Pull Request do?
Most of this is @dbernstein's work from before, I just dragged it across a line.

# What's new?
I checked out a bunch of things from @dbernstein's update-fcrepo-parent-pom branch but stuck with the older versions of dependencies. 

# How should this be tested?

Should build and then you could try testing it out. I am going to try it in fcrepo-vagrant soon.

# Additional Notes:

Example:
* Does this change require documentation to be updated? no
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

# Interested parties
@peichman-umd @birkland @dbernstein or any other interested @fcrepo4/committers

### CODE REVIEW

**Comment by whikloj** [comment]
I hope this works for you all, but it passed on my machine and I was like James Brown dancing

**Comment by whikloj** [comment]
Failure is due to log length, log length is due to seemingly a tonne of duplicate class in the Fedora war.

**Comment by whikloj** [comment]
So yeah, Shiro seems to have classes included in multiple places or maybe its just the way Jetty scans but I started to try and exclude some artifacts in fcrepo-webapp and realized I had to pretty much exclude everything. So either we have waaay to much of shiro included as dependencies or Jetty 9.3 is just causing trouble

**Comment by whikloj** [comment]
Yeah I maybe I don't understand what Shiro is trying to do but they have the same classes in different packages and then they have dependencies between those packages (ie. `shiro-config-ogdl` has a dependency on `shiro-config-core`)?
```
[/Users/whikloj/.m2/repository/org/apache/shiro/shiro-config-ogdl/1.4.0] 
> unzip -t shiro-config-ogdl-1.4.0.jar | grep ConfigurationException -
    testing: org/apache/shiro/config/ConfigurationException.class   OK

[/Users/whikloj/.m2/repository/org/apache/shiro/shiro-config-core/1.4.0] 
> unzip -t shiro-config-core-1.4.0.jar | grep ConfigurationException -
    testing: org/apache/shiro/config/ConfigurationException.class   OK
```

**Comment by whikloj** [comment]
Ok this is an open issue for Shiro https://issues.apache.org/jira/browse/SHIRO-632

**Comment by dbernstein** [comment]
@whikloj : I'm going to put a picture of you on my desk and recall the good that you have done each day.  YES! It works and has taught me the value of restraint when it comes to unnecessary dependency updates.

**Comment by dbernstein** [comment]
@whikloj: Looks like it needs a rebasing as well when you get a chance.

**Comment by whikloj** [comment]
@dbernstein I'll rebase this, I also want to see if I can bump the camel version 2.20 as that would alleviate the security warnings.

I'll also note it wasn't necessarily the dependencies causing the problems, two of the tests in fcrepo-service-camel were actually failing.

We used to emit 2 messages for a CREATE (one for the item and one for the parent). But now we emit 3 (one for item, one for parent and one for versions container).

**Pull request merged**
