### PR TITLE
Updates for migrating from standalone Fuseki to fuseki.war. Address F…

### PR DESCRIPTION
**Pull request by ruebot**
…CREPO-1467.

https://jira.duraspace.org/browse/FCREPO-1467

### CODE REVIEW

**Comment by ajs6f** [comment]
I have nothing against this PR, but Fuseki 1 _is_ getting a bit longer in the tooth and Fuseki 2 is clearly where the Jena folks are putting more attention. See [here](https://github.com/ocymum/trippi-sparql-update/blob/master/pom.xml) for an example of how to use Fuseki 2 to support integration tests with the Maven plugin for Cargo.

**Comment by ajs6f** [comment]
I don't care at all about `fcrepo4-vagrant` in this context (not saying it's unimportant, just saying it doesn't matter to me when looking at ITs _here_). Generally, I'm saying we should move to Fuseki 2 in _all_ places. Including these ITs.

**Comment by ajs6f** [comment]
Because `EmbeddedFusekiServer` is a Fuseki 1 class.

**Comment by acoburn** [comment]
The current integration test uses fuseki 1.1.1, and I am also in favor of moving that to 2.x, but this PR is completely unrelated to that. That is, this PR is about updating the default properties so that they assume a war-deployed fuseki rather than a standalone fuseki.

**Comment by acoburn** [comment]
@ruebot that would be great, thanks

**Comment by ajs6f** [comment]
If they are assuming a war-deployed Fuseki, why is there any use of `EmbeddedFusekiServer`?

**Comment by acoburn** [comment]
@ajs6f the EmbeddedFusekiServer class is for doing integration tests. The vagrant project is for actually running the fuseki server.

**Comment by ajs6f** [comment]
Urg, that's my point. If this PR is about relying on a deployed WAR, then using `EmbeddedFusekiServer` is a fail, _because it is exactly relying on something other than  a WAR_.

**Comment by acoburn** [comment]
@ajs6f The point of the integration test in question is to test how the camel route interacts with an HTTP endpoint backed by some triplestore. In this case it happens to be fuseki. My point is that it shouldn't matter what version or what deployment strategy is used for that HTTP endpoint: the endpoint should be the same. The camel route is completely indifferent about what triplestore is used and what deployment strategy is used for that triplestore.

**Comment by ajs6f** [comment]
Sure. This isn't about the validity of the test. It's about the dependency footprint (which is _always_ an issue) and whether the tests are useful in explaining to people how to set up their own integrations, which is one of the purposes of writing integration tests. As long as it gets fixed, I don't really care where it gets fixed, in this PR or another, but using `EmbeddedFusekiServer` is outdated practice and we shouldn't be doing it.

**Comment by acoburn** [comment]
@ajs6f That's a fair point, and I agree about updating fuseki. Do you have a preference between `cargo-maven2-plugin` and `jetty-maven-plugin`? (We're currently using jetty for other tests, but I'm not particularly attached to it)

**Comment by ajs6f** [comment]
I'm inclined towards Cargo because it generalizes (e.g. you can quickly install profiles to test in other containers, which is a really good habit that we rarely evidence.).

**Comment by awoods** [comment]
It sounds like we have landed on moving towards a cargo-based, war deployment of Fuseki2 for the integration tests in this project... per the ticket created by @ruebot:
https://jira.duraspace.org/browse/FCREPO-1708

Otherwise, this current PR looks good. Are there objections to moving the PR into master? ...pending more testing.

**Comment by acoburn** [comment]
I'm :+1: on merging this PR with master, provided it works well with the vagrant setup

**Pull request merged**
