### PR TITLE
Fix broken reindexing

### PR DESCRIPTION
**Pull request by acoburn**
Update reindexing code to properly use the `camel-jetty` component in exposing an HTTP endpoint.

Resolves: https://jira.duraspace.org/browse/FCREPO-1980

### CODE REVIEW

**Comment by awoods** [comment]
I would expect this type of basic failure to be caught by an integration test. With pax-exam in place, I thought that was now possible. Can an integration test by added to this PR?

**Comment by acoburn** [comment]
@awoods integration test added.

**Comment by awoods** [comment]
The integration test fails for me... port conflict with other local services.

**Comment by acoburn** [comment]
@awoods: yes, I suppose that would be a problem. I'll fix that.

**Comment by acoburn** [comment]
@awoods: pax exam is now using a dynamic port configuration

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/commit/a1a92c87e33696e5a532c2506b9d78bff0592df0

**Pull request closed without merging**
