### PR TITLE
Add support for https connections to external triplestores

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-2087

### CODE REVIEW

**Comment by acoburn** [comment]
I would note here that in this PR, I'm really just cribbing from @mohideen's excellent contribution: https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/commit/2488daf5abd3db4ee0130e7082bf7c66916674c2

**Comment by mohideen** [comment]
Thanks for taking care of this @acoburn! I wanted to get to it, but this was a busy week.

**Comment by acoburn** [comment]
@dannylamb now that you're back, is there any chance you can review this PR?

**Comment by dannylamb** [comment]
@acoburn no problem.  looking through the PR, it certainly seems to do what is expected.  let me give it a smoke test before pulling the trigger.

**Comment by acoburn** [comment]
Could someone please review/merge this?

**Comment by dannylamb** [comment]
Reviewed, compiled, and successfully deployed.

**Comment by ajs6f** [comment]
@acoburn ++ ! @dannylamb ++ !

**Pull request merged**
