### PR TITLE
Separate blueprint from java code

### PR DESCRIPTION
**Pull request by acoburn**
Resolves: https://jira.duraspace.org/browse/FCREPO-2339

There are some minor code changes here (e.g. resource paths must now be scoped to the exported package names), but this is mostly some Maven shuffling.

### CODE REVIEW

**Comment by birkland** [comment]
This looks good via looking at the diffs.  I have not had a chance to run it manually in Karaf yet, but will do so at some point during the day

**Comment by birkland** [comment]
Is there a way to install a toolbox application as a feature *without* any blueprint config?  For some reason, I thought that the features.xml file would contain features that pull in bundles + blueprint in a backwards compatible manner (e.g. `feature:install fcrepo-ldpath` would have the same net result as it does today), *and* would contain features that pull in everything except the blueprint; for those that want alternate configurations or multiple configurations.

for example:
* `feature:install fcrepo-ldpath-impl` - pulls in just the ldpath bundle + dependencies, but *no* blueprint
* `feature:install fcrepo-ldpath` - pulls in ldpath bundle + dependencies + blueprint (i.e. `fcrepo-ldpath-impl` + `fcrepo-ldpath-blueprint`)

So this PR has the latter but not the former, as far as I can tell.  I think it'd be just a matter of tweaking the features file to do so.   @acoburn Do you think that would be worthwhile?  If not, I'd be OK merging it anyway

**Comment by acoburn** [comment]
@birkland there is _not_ a way to install a toolbox application without the blueprint configuration (using the existing `features.xml` file). I had considered that possibility, but then decided against it -- though I don't really have strong reasons against it. And yes, it would simply be a matter of tweaking the existing `features.xml`. Making that change seems perfectly reasonable, and it would even be sort of nice for some things I'd like to do. I can either update this PR with that change, or I can do that as part of a separate ticket.

**Comment by birkland** [comment]
How about we merge now and do a separate ticket.  Sound good?

**Comment by acoburn** [comment]
That sounds good to me. Thanks @birkland!

**Pull request merged**
