### PR TITLE
omit ldp:contains triples from representation

### PR DESCRIPTION
**Pull request by acoburn**
See: https://jira.duraspace.org/browse/FCREPO-1849

### CODE REVIEW

**Comment by escowles** [comment]
Would it be hard to parameterize this, so a user could configure any `Prefer` headers?  That seems like it could be even more useful.

**Comment by ajs6f** [comment]
Is there some LDP-spec way to do that? It would be nice to stay aligned there. Is `PreferContainment` our own thing?

**Comment by lisp** [comment]
good afternoon;

> On 2015-12-01, at 14:31, A. Soroka <notifications@github.com> wrote:
> 
> Is there some LDP-spec way to do that? It would be nice to stay aligned there. Is PreferContainment our own thing?
> 
> 

see: http://www.w3.org/TR/ldp/#prefer-parameters

best regards, from berlin,
---
james anderson | james@dydra.com | http://dydra.com

**Comment by ajs6f** [comment]
Right, that's in the LDP namespace. Ours isn't. Unless that something the `fcrepo` component does "magically" (booh!)?

**Comment by acoburn** [comment]
This change uses the standard LDP-defined Prefer header:

    Prefer: return=representation; omit="http://www.w3.org/ns/ldp#PreferContainment"

I could certainly make this configurable as @escowles suggests, but I think it is a bad idea to allow it. The reason is that, for a repository of any significant size, the root node (or, in the case of many hydra instances: the `/prod` node) will contain `ldp:contains` links to all of the children. The size of the response is unbounded, and expecting to pass that into a triplestore (let alone expect that it will fit into memory on the camel machine) becomes really problematic. And any time a new resource is added to that node (e.g. `/prod`), an event is triggered to re-index not only the new node but also that root node, which means that the processing required will quickly exceed the available resources.

In a word, making this configurable, is asking for trouble. I think we should just omit those triples.

**Comment by ajs6f** [comment]
So the string `PreferContainment` in this PR is automatically prefixed with the LDP namespace? How, then, would anyone ever use a value for that header that _isn't_ part of the LDP namespace?

**Comment by acoburn** [comment]
The short forms `PreferContainment` and `PreferMembership` (along with the fedora-isms of EmbedResources, etc) are automatically expanded to the correct URIs. But it is also possible to use the full URIs with the `?preferOmit=` argument. The argument `?preferOmit=PreferContainment` is equivalent to writing `?preferOmit=http://www.w3.org/ns/ldp#PreferContainment`

**Comment by ajs6f** [comment]
@acoburn What about the use case of "spidering" a repo into a triplestore for some other kind of action? The `ldp:contains` stuff would be important for that.

**Comment by ajs6f** [comment]
@acoburn The question I am asking is: how do you send a value for that header that is _not_ in the LDP namespace? How does the component know which values to auto-prefix?

**Comment by acoburn** [comment]
@ajs6f The component auto-prefixes these values: https://github.com/fcrepo4-exts/fcrepo-camel/blob/master/src/main/java/org/fcrepo/camel/RdfNamespaces.java#L37-L43

**Comment by acoburn** [comment]
@ajs6f I agree that `ldp:contains` is an important property and that there are valid use cases for it, but couldn't you simply use a reasoner that knows that `ldp:contains` is an inverse property to `fedora:hasParent`? That, I think, would be a much better approach than pushing all of those triples through the triplestore's HTTP interface.

**Comment by ajs6f** [comment]
I'm really chary of asking anyone to use a reasoner for anything. I mean, _I_ would definitely do it the way you describe, but there are reasons not to require it. Also, if we are talking about preservation concerns, and we might be, the reasoner scenario is right out, I think, for most people. (Wrongly, I think, but there you are.)

**Comment by ajs6f** [comment]
@acoburn Okay, cool. That's reasonable. (The URI prefixing mechanic.)

**Comment by acoburn** [comment]
OK, so it sounds like the consensus is for making the `ldp:contains` triples configurable. I'll update the PR with that change.

**Comment by acoburn** [comment]
I have updated this PR to make the Prefer: headers configurable.

**Comment by escowles** [comment]
:+1: looks good to me.

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/commit/25c51cb331347c914b821ed1c084f62e567102f8

**Pull request closed without merging**
